name: Deploy MERN Chat App

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend to Render
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Vercel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

     - name: Deploy to Vercel
  run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes


